name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies (apt)
        run: |
          sudo apt-get update && \
          sudo apt-get install -y --no-install-recommends \
          libxi-dev libgl1-mesa-dev
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install Dependencies
        run: yarn install
      - name: Build Site
        run: yarn build --base=/frontend2/
        env:
          VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          VITE_SICP_BACKEND_URL: ${{ secrets.VITE_SICP_BACKEND_URL }}
          VITE_FEATURE_ENABLE_SOURCE: ${{ secrets.VITE_FEATURE_ENABLE_SOURCE }}
          VITE_FEATURE_ENABLE_FULL_JS: ${{ secrets.VITE_FEATURE_ENABLE_FULL_JS }}
          VITE_FEATURE_ENABLE_FULL_TS: ${{ secrets.VITE_FEATURE_ENABLE_FULL_TS }}
          VITE_FEATURE_ENABLE_HTML: ${{ secrets.VITE_FEATURE_ENABLE_HTML }}
          VITE_FEATURE_ENABLE_PYTHON: ${{ secrets.VITE_FEATURE_ENABLE_PYTHON }}
          VITE_FEATURE_ENABLE_SCHEME: ${{ secrets.VITE_FEATURE_ENABLE_SCHEME }}
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
